# This file is used for development, not for production!

version: "3.4"

services:
  nginx:
    image: course-nginx
    container_name: course-nginx
    hostname: course-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    networks:
      - nginx
    depends_on:
      - course-frontend
      - course-backend
      - course-distribute-server
      - course-mongodb
      - course-redisdb

  course-frontend:
    image: course-frontend-dev
    build:
      context: .
      dockerfile: ./dev-support/frontend/Dockerfile
    container_name: course-frontend-dev
    expose:
      - "3000"
    networks:
      - nginx
    environment:
      - REACT_APP_API_HOST=https://course.ntuee.org
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - "course-backend"

  course-backend:
    image: course-backend-dev
    build:
      context: .
      dockerfile: ./dev-support/backend/Dockerfile
    container_name: course-backend-dev
    expose:
      - "8000"
    networks:
      - nginx
    environment:
      - MONGO_HOST=course-mongodb
      - REDIS_HOST=course-redisdb
      - DISTRIBUTE_SERVER_HOST=course-distribute-server
      - DISTRIBUTE_SERVER_PORT=8001
    links:
      - "course-distribute-server"

  course-mongodb:
    image: mongo
    container_name: course-mongodb-dev
    expose:
      - "27017"
    networks:
      - nginx
    volumes:
      - course-mongo:/data/db

  course-redisdb:
    image: redis
    container_name: course-redisdb-dev
    expose:
      - "6379"
    networks:
      - nginx

  course-distribute-server:
    image: course-distribute-server-dev
    build:
      context: .
      dockerfile: ./dev-support/distribute-server/Dockerfile
    container_name: course-distribute-server-dev
    expose:
      - "8001"
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  course-mongo:
